language: objective-c
sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode10.2

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

script:
  - csrutil status
  - git submodule update --init --recursive
  - APPMAP=true bundle exec rspec spec

after_script:
- env DEBUG=true ruby ./upload-appmaps tmp/appmap/rspec/*
